# Generated by Django 5.2.16 on 2026-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_types'),
        ),
    ]
