# Generated by Django 5.2.16 on 2026-07-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_professional_booking_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.professional'),
        ),
    ]
