# Generated by Django 5.2.16 on 2026-07-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_booking_professional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
