# Generated by Django 5.2.16 on 2026-07-16 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='otp',
            name='channel',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('email', 'Email')], default='mobile', max_length=10),
        ),
        migrations.AddField(
            model_name='otp',
            name='identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('forgot_password', 'Forgot Password')], default='register', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='accounts_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='accounts_user_permissions', to='auth.permission'),
        ),
    ]
