# Generated by Django 5.2.16 on 2026-07-14 12:14

import django.db.models.deletion
import professionals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_governorate_is_active'),
        ('services', '0004_servicetype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='professionals')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('jobs_done', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.PositiveIntegerField(default=100)),
                ('cancellations', models.PositiveIntegerField(default=0)),
                ('avg_arrival_minutes', models.PositiveIntegerField(default=15)),
                ('next_available_date', models.DateField(blank=True, null=True)),
                ('next_available_time', models.TimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='locations.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=professionals.models.generate_booking_code, max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mobile', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('area', models.CharField(max_length=100)),
                ('villa_apartment_no', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=150)),
                ('building_floor', models.CharField(blank=True, max_length=100)),
                ('nearest_landmark', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('payment_method', models.CharField(choices=[('bank_of_muscat_card', 'Bank of Muscat Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('thawani', 'Thawani'), ('cash_on_completion', 'Cash on Completion')], default='cash_on_completion', max_length=30)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('save_card', models.BooleanField(default=False)),
                ('service_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('platform_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('vat_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.servicetype')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='professionals.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professionals.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='professionals.professional')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='services.servicetype')),
            ],
            options={
                'unique_together': {('professional', 'service_type')},
            },
        ),
    ]
