# Generated by Django 5.2.16 on 2026-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professional_user_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
