# Generated by Django 5.2.16 on 2026-07-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_professional_email_professional_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='professionals.professional')),
            ],
            options={
                'unique_together': {('professional', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionalServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_prices', to='professionals.professionalservicetype')),
            ],
            options={
                'unique_together': {('offering', 'area')},
            },
        ),
    ]
