# Generated by Django 5.2.16 on 2026-08-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_add_vendor_bank_and_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('custom', 'Custom')], max_length=50, unique=True)),
                ('price_omr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credits', models.PositiveIntegerField()),
                ('leads_per_mo', models.PositiveIntegerField(default=0)),
                ('dispatch_priority', models.CharField(default='standard', max_length=30)),
                ('ai_job_matching', models.BooleanField(default=False)),
                ('support_level', models.CharField(default='email', max_length=30)),
                ('dedicated_manager', models.BooleanField(default=False)),
                ('custom_sla', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('plan_renewal', 'Plan Renewal'), ('booking_lead', 'Booking Lead'), ('admin_bonus', 'Admin Bonus'), ('manual_topup', 'Manual Top-up'), ('refund', 'Refund')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.booking')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='professionals.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_label', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='professionals.professional')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('renews_at', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professionals.subscriptionplan')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='professionals.professional')),
            ],
        ),
    ]
