# Generated by Django 5.2.16 on 2026-09-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0010_add_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('live', 'Live'), ('setup', 'Setup'), ('connected', 'Connected'), ('disabled', 'Disabled')], default='setup', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('live', 'Live'), ('setup', 'Setup'), ('disabled', 'Disabled')], default='setup', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_pct', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('vat_rate_pct', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('payout_cycle', models.CharField(default='T+1', max_length=10)),
                ('currency', models.CharField(default='OMR', max_length=10)),
                ('currency_decimals', models.PositiveSmallIntegerField(default=3)),
                ('default_languages', models.CharField(default='EN + AR', max_length=50)),
                ('auto_routing_ai_enabled', models.BooleanField(default=True)),
                ('ai_moderation_enabled', models.BooleanField(default=True)),
                ('max_jobs_per_vendor_per_day', models.PositiveIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('cr_number', models.CharField(blank=True, max_length=50)),
                ('cr_verified', models.BooleanField(default=False)),
                ('oman_id_status', models.CharField(blank=True, max_length=50)),
                ('oman_id_verified', models.BooleanField(default=False)),
                ('business_type', models.CharField(choices=[('llc', 'LLC Company'), ('sole_proprietor', 'Sole Proprietor'), ('individual', 'Individual')], default='llc', max_length=30)),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('working_days', models.CharField(blank=True, max_length=50)),
                ('max_jobs_per_day', models.PositiveIntegerField(default=4)),
                ('emergency_callouts_enabled', models.BooleanField(default=False)),
                ('emergency_callout_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_online', models.BooleanField(default=True)),
                ('notify_new_booking', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('notify_review_posted', models.BooleanField(default=True)),
                ('notify_credits_low', models.BooleanField(default=True)),
                ('notify_weekly_earnings', models.BooleanField(default=True)),
                ('notify_ai_tips', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='professionals.professional')),
            ],
        ),
    ]
