# Generated by Django 5.2.16 on 2026-09-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0011_integration_paymentgateway_platformconfig_and_more'),
    ]

    operations = [
    ]
