# Generated by Django 5.2.16 on 2026-09-18 10:39

from django.db import migrations


def seed_data(apps, schema_editor):
    PaymentGateway = apps.get_model('professionals', 'PaymentGateway')
    Integration = apps.get_model('professionals', 'Integration')

    PaymentGateway.objects.bulk_create([
        PaymentGateway(name="Bank of Muscat", description="OMR cards · Maisarah · Primary", status="live",  is_primary=True, sort_order=1),
        PaymentGateway(name="Thawani Pay",    description="Oman local debit · OTTP",        status="live",  sort_order=2),
        PaymentGateway(name="Stripe",         description="Intl · Apple Pay · Google Pay",  status="live",  sort_order=3),
        PaymentGateway(name="OmanNet",        description="Debit · In progress",            status="setup", sort_order=4),
    ])

    Integration.objects.bulk_create([
        Integration(name="Unifonic SMS", description="OTP · Booking SMS · EN+AR", status="live",      sort_order=1),
        Integration(name="Firebase",     description="FCM Push · OTP Auth",       status="live",      sort_order=2),
        Integration(name="Google Maps",  description="Tracking · Directions",     status="live",      sort_order=3),
        Integration(name="MOCI API",     description="CR Verification",           status="connected", sort_order=4),
        Integration(name="ROP API",      description="Civil ID Verify",           status="connected", sort_order=5),
        Integration(name="WhatsApp Biz", description="Order alerts",              status="setup",     sort_order=6),
        Integration(name="Claude AI",    description="NLP search · Moderation",  status="live",      sort_order=7),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0012_seed_gateways_integrations'),  # ← keep this exactly as is
    ]

    operations = [
        migrations.RunPython(seed_data, migrations.RunPython.noop),  # ← add this
    ]