# Generated by Django 5.2.16 on 2026-09-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0013_seed_gateways_integrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_id_number', models.CharField(blank=True, max_length=50)),
                ('civil_id_verified', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('certification_name', models.CharField(blank=True, max_length=100)),
                ('certification_verified', models.BooleanField(default=False)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='vendor_docs/id_copy/')),
                ('trade_license_doc', models.FileField(blank=True, null=True, upload_to='vendor_docs/trade_license/')),
                ('certification_doc', models.FileField(blank=True, null=True, upload_to='vendor_docs/certification/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('docs_requested', 'Docs Requested')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_docs_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='professionals.professional')),
            ],
            options={
                'verbose_name': 'Vendor Verification',
            },
        ),
    ]
