# Generated by Django 5.2.16 on 2026-09-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0014_vendorverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_code', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('ai_risk', models.CharField(blank=True, choices=[('high', 'High Risk'), ('medium', 'Medium Risk'), ('low', 'Low Risk'), ('auto_resolved', 'Auto-resolved')], max_length=20, null=True)),
                ('is_auto_resolved', models.BooleanField(default=False)),
                ('resolution_action', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='professionals.booking')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='professionals.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
