# Generated by Django 5.2.16 on 2026-09-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0015_dispute'),
        ('services', '0007_remove_booking_professional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon_emoji', models.CharField(default='🏷️', max_length=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_label', models.CharField(blank=True, max_length=50)),
                ('target_segment', models.CharField(default='All Muscat', max_length=150)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('expired', 'Expired'), ('paused', 'Paused')], default='live', max_length=20)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('conversion_rate_pct', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('discount_cost', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('ai_recommendation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
