# Generated by Django 5.2.16 on 2026-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
